[phases.setup]
nixPkgs = [
  'redis',
  'qpdf',
  'ghostscript',
  'tesseract5',
  'wkhtmltopdf',
  'libreoffice-fresh',
  'pixman',
  'librsvg',
  'giflib',
  'libjpeg',
  'pango',
  'cairo',
  'pkg-config',
  'libuuid'
]
