'use client'

import { useRef, useState } from 'react'
import { Check, Download, FileSignature, FileUp, Minus, PenLine, Plus, Redo2, RotateCcw, Trash2, Undo2, Upload, X } from 'lucide-react'
import { PDFDocument, rgb } from 'pdf-lib'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { pdfSizeToViewer } from '@/lib/sign-pdf-coordinates'

const MAX_FILE_SIZE = 25 * 1024 * 1024
const PAGE = { width: 612, height: 792 }
type Item = { id: string; kind: 'signature' | 'initials' | 'name' | 'date' | 'text' | 'checkbox'; x: number; y: number; width: number; height: number; value: string }
type History = Item[][]

function makeItem(kind: Item['kind'], value = ''): Item { return { id: crypto.randomUUID(), kind, value, x: 72, y: 500, width: kind === 'signature' ? 170 : 120, height: kind === 'signature' ? 65 : 28 } }

export function SignPdfClient() {
  const inputRef = useRef<HTMLInputElement>(null); const canvasRef = useRef<HTMLCanvasElement>(null); const pageRef = useRef<HTMLDivElement>(null)
  const [file, setFile] = useState<File | null>(null); const [pdfUrl, setPdfUrl] = useState(''); const [items, setItems] = useState<Item[]>([]); const [past, setPast] = useState<History>([]); const [future, setFuture] = useState<History>([])
  const [signature, setSignature] = useState(''); const [name, setName] = useState(''); const [tab, setTab] = useState('draw'); const [scale, setScale] = useState(1); const [selected, setSelected] = useState(''); const [error, setError] = useState(''); const [drawing, setDrawing] = useState(false)
  const commit = (next: Item[]) => { setPast((h) => [...h, items]); setFuture([]); setItems(next) }
  const chooseFile = async (f?: File) => { const next = f ?? inputRef.current?.files?.[0]; if (!next) return; if (next.type !== 'application/pdf' || !next.name.toLowerCase().endsWith('.pdf')) return setError('Choose a valid PDF file.'); if (next.size > MAX_FILE_SIZE) return setError('PDFs must be smaller than 25 MB.'); try { await PDFDocument.load(await next.arrayBuffer()); const url = URL.createObjectURL(next); setPdfUrl(url); setFile(next); setItems([]); setError('') } catch { setError('This PDF could not be opened.') } }
  const startDraw = (e: React.PointerEvent<HTMLCanvasElement>) => { const c = canvasRef.current; if (!c) return; c.setPointerCapture(e.pointerId); const r = c.getBoundingClientRect(); const ctx = c.getContext('2d'); if (!ctx) return; ctx.lineWidth = 3; ctx.lineCap = 'round'; ctx.strokeStyle = '#172554'; ctx.beginPath(); ctx.moveTo(e.clientX-r.left, e.clientY-r.top); setDrawing(true) }
  const draw = (e: React.PointerEvent<HTMLCanvasElement>) => { if (!drawing) return; const c = canvasRef.current; const ctx = c?.getContext('2d'); if (!c || !ctx) return; const r = c.getBoundingClientRect(); ctx.lineTo(e.clientX-r.left, e.clientY-r.top); ctx.stroke() }
  const saveDraw = () => { const c = canvasRef.current; if (!c) return; setSignature(c.toDataURL('image/png')); setTab('draw') }
  const addItem = (kind: Item['kind'], value = '') => { const item = makeItem(kind, value); commit([...items, item]); setSelected(item.id) }
  const updateItem = (id: string, patch: Partial<Item>) => commit(items.map((i) => i.id === id ? { ...i, ...patch } : i))
  const download = async () => { if (!file) return; try { const doc = await PDFDocument.load(await file.arrayBuffer()); const pages = doc.getPages(); const page = pages[0]; for (const item of items) { const x = item.x, y = item.y; if (item.kind === 'signature' && signature) { const image = await doc.embedPng(signature); page.drawImage(image, { x, y, width: item.width, height: item.height }) } else if (item.kind === 'checkbox') page.drawRectangle({ x, y, width: 14, height: 14, borderColor: rgb(0.1,0.2,0.5), borderWidth: 1 }); else page.drawText(item.value || item.kind, { x, y: y + 7, size: 12, color: rgb(0.08,0.1,0.2) }) } const blob = new Blob([await doc.save()], { type: 'application/pdf' }); const a = document.createElement('a'); a.href = URL.createObjectURL(blob); a.download = file.name.replace(/\.pdf$/i, '') + '-signed.pdf'; a.click() } catch { setError('Export failed. Please try another PDF.') } }
  const rect = pageRef.current?.getBoundingClientRect(); const viewer = rect ? { left: 0, top: 0, width: rect.width, height: rect.height } : { left: 0, top: 0, width: 612, height: 792 }
  return <main className="min-h-screen bg-background text-foreground"><header className="border-b bg-card"><div className="mx-auto flex max-w-[1500px] items-center justify-between gap-4 px-4 py-3"><div className="flex items-center gap-3"><div className="flex size-9 items-center justify-center rounded-lg bg-primary text-primary-foreground"><FileSignature /></div><div><p className="font-semibold">Sign PDF</p><p className="text-xs text-muted-foreground">Private document workspace</p></div></div><div className="flex items-center gap-2"><Button variant="outline" size="sm" disabled={!past.length} onClick={() => { const previous = past[past.length-1]; setFuture((h) => [items, ...h]); setPast((h) => h.slice(0,-1)); setItems(previous) }}><Undo2 data-icon="inline-start" />Undo</Button><Button variant="outline" size="sm" disabled={!future.length} onClick={() => { const next = future[0]; setPast((h) => [...h, items]); setFuture((h) => h.slice(1)); setItems(next) }}><Redo2 data-icon="inline-start" />Redo</Button><Button size="sm" disabled={!file} onClick={download}><Download data-icon="inline-start" />Export signed PDF</Button></div></div></header><div className="mx-auto grid max-w-[1500px] gap-4 p-4 lg:grid-cols-[190px_minmax(400px,1fr)_290px]">
    <Card className="hidden lg:block"><CardHeader><CardTitle className="text-sm">Pages</CardTitle></CardHeader><CardContent><div className="flex aspect-[8.5/11] items-center justify-center border bg-muted text-xs text-muted-foreground">{file ? 'Page 1' : 'No PDF'}</div><p className="mt-2 text-xs text-muted-foreground">One-page signing view</p></CardContent></Card>
    <section className="flex min-h-[620px] flex-col gap-3 rounded-xl border bg-muted/40 p-3"><div className="flex items-center justify-between"><div className="flex items-center gap-1"><Button variant="outline" size="icon-sm" onClick={() => setScale((s) => Math.max(.6,s-.1))} aria-label="Zoom out"><Minus /></Button><span className="w-14 text-center text-sm">{Math.round(scale*100)}%</span><Button variant="outline" size="icon-sm" onClick={() => setScale((s) => Math.min(1.6,s+.1))} aria-label="Zoom in"><Plus /></Button></div><Button variant="ghost" size="sm" onClick={() => setFile(null)} disabled={!file}><X data-icon="inline-start" />Close</Button></div>{!file ? <div className="flex flex-1 flex-col items-center justify-center gap-4 text-center"><FileUp className="size-12 text-primary" /><h1 className="text-2xl font-semibold">Sign your PDF securely</h1><p className="max-w-md text-sm leading-6 text-muted-foreground">Add visual electronic signatures and form fields locally in your browser. Your file is never uploaded.</p><Button onClick={() => inputRef.current?.click()}><Upload data-icon="inline-start" />Choose PDF</Button><input ref={inputRef} type="file" accept="application/pdf" className="sr-only" onChange={() => chooseFile()} />{error && <p role="alert" className="text-sm text-destructive">{error}</p>}</div> : <div className="flex flex-1 items-center justify-center overflow-auto p-2"><div ref={pageRef} className="relative shrink-0 overflow-hidden bg-card shadow-lg" style={{ width: 612*scale, height: 792*scale }}><embed src={pdfUrl} type="application/pdf" className="pointer-events-none absolute inset-0 size-full" /><div className="absolute inset-0">{items.map((item) => { const s = pdfSizeToViewer(item, PAGE, viewer); return <button key={item.id} className={`absolute border-2 ${selected===item.id ? 'border-primary bg-primary/10' : 'border-transparent hover:border-primary/50'}`} style={{ left: item.x*scale, top: (PAGE.height-item.y-item.height)*scale, width: s.width, height: s.height }} onClick={() => setSelected(item.id)} onKeyDown={(e) => { if (e.key === 'Delete') commit(items.filter((x)=>x.id!==item.id)) }} aria-label={`${item.kind} field`}>{item.kind === 'signature' ? <img src={signature} alt="Signature" className="size-full object-contain" /> : item.kind === 'checkbox' ? <Check className="size-full p-1" /> : <span className="text-xs">{item.value || item.kind}</span>}</button>})}</div></div></div>}</section>
    <Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><PenLine className="size-4 text-primary" />Tools</CardTitle><CardDescription>Add fields and create your signature.</CardDescription></CardHeader><CardContent className="flex flex-col gap-4"><div className="grid grid-cols-2 gap-2">{(['name','date','text','checkbox','initials'] as const).map((kind) => <Button key={kind} variant="outline" size="sm" onClick={() => addItem(kind, kind === 'name' ? name : kind === 'date' ? new Date().toLocaleDateString() : '')}>{kind[0].toUpperCase()+kind.slice(1)}</Button>)}</div><Tabs value={tab} onValueChange={setTab}><TabsList className="grid w-full grid-cols-2"><TabsTrigger value="draw">Draw</TabsTrigger><TabsTrigger value="type">Type</TabsTrigger></TabsList><TabsContent value="draw" className="flex flex-col gap-2"><canvas ref={canvasRef} width={600} height={180} className="h-32 w-full touch-none rounded-md border bg-card" onPointerDown={startDraw} onPointerMove={draw} onPointerUp={() => setDrawing(false)} onPointerLeave={() => setDrawing(false)} /><div className="flex gap-2"><Button variant="outline" size="sm" onClick={() => canvasRef.current?.getContext('2d')?.clearRect(0,0,600,180)}><RotateCcw data-icon="inline-start" />Clear</Button><Button size="sm" onClick={() => { saveDraw(); addItem('signature') }}>Use signature</Button></div></TabsContent><TabsContent value="type" className="flex flex-col gap-2"><Label htmlFor="signer">Name</Label><Input id="signer" value={name} onChange={(e)=>setName(e.target.value)} placeholder="Your full name" /><div className="rounded-md border p-4 text-center font-serif text-2xl italic">{name || 'Your signature'}</div><Button onClick={() => { const c=canvasRef.current; const ctx=c?.getContext('2d'); if(!c||!ctx)return; ctx.clearRect(0,0,600,180); ctx.font='italic 54px Georgia'; ctx.fillStyle='#172554'; ctx.fillText(name || 'Your name', 24, 100); saveDraw(); addItem('signature') }}>Use typed signature</Button></TabsContent></Tabs>{signature && <div className="flex items-center justify-between rounded-md bg-muted p-2 text-sm"><span>Signature ready</span><Button variant="ghost" size="icon-sm" onClick={()=>setSignature('')}><Trash2 /></Button></div>}{error && <p role="alert" className="text-sm text-destructive">{error}</p>}<p className="text-xs leading-5 text-muted-foreground">Visual electronic signature only. This tool does not create a certificate-based digital signature or verify identity.</p></CardContent></Card></div></main>
}
